### ISSUE TITLE
Passing params to callback function

### ISSUE THREAD

**Issue by toymachiner62** [node-cron/node-cron#160]
I'm creating a scheduler and exporting it as a function.

I need to be able to pass in params to my callback function and node-cron is choking on this.

For example this works:
```js
const cron = require('node-cron')

// Does not work
function scheduler () {
  cron.schedule('*/1 * * * *', doStuff) // This works as i'm just referencing the function
}

function doStuff () {
  console.log('in doStuff. The time is ', new Date())
}

module.exports = scheduler
```

This does not:
```js
const cron = require('node-cron')

// Does not work
function scheduler () {
  cron.schedule('*/1 * * * *', doStuff('fido')) // This does NOT work
}

function doStuff () {
  console.log('in doStuff. The time is ', new Date())
}

module.exports = scheduler
```
and it gives the error:
```sh
$ npm start

> schedule@1.0.0 start /Users/tomcaflisch/Sites/schedule
> node index.js

starting
in doStuff. My dogs name is foo. The time is  2019-03-27T23:36:56.253Z
TypeError: this.execution is not a function
    at Promise (/Users/tomcaflisch/Sites/schedule/node_modules/node-cron/src/task.js:52:23)
    at new Promise (<anonymous>)
    at Task.update (/Users/tomcaflisch/Sites/schedule/node_modules/node-cron/src/task.js:50:7)
    at Timeout.ScheduledTask.task [as _onTimeout] (/Users/tomcaflisch/Sites/schedule/node_modules/node-cron/src/scheduled-task.js:86:10)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

any way around this other than setting variables in my `scheduler()` function and then making them global-ish?

**Comment by travis5491811** [comment]
@toymachiner62, `node-cron` expects a function to execute, not one that is already executed.

```JavaScript
const doStuff = () => console.log('doing stuff');
const x = doStuff;
typeof x
// > 'function'
const y = doStuff();
typeof y
// 'undefined'
```

Pass your parameter(s) to the parent function
```JavaScript
const cron = require('node-cron')

function scheduler (fido) {
  cron.schedule('*/1 * * * *', () => doStuff(fido));
  console.log(`Scheduler 1 activated: ${new Date()}`);
}

// OR
// function scheduler (fido) {
//   cron.schedule('*/1 * * * *', () => {
//     try {
//       doStuff(fido);        
//     } catch (error) {
//       console.log('error', error);
//     }
//   });
//   console.log(`Scheduler 2 activated: ${new Date()}`);
// }


function doStuff (p) {
  const msg = `Running task with params "${p}" in doStuff. The time is: ${new Date()}`;
  console.log(msg);
};

scheduler('fido');
```

**Comment by minasvisual** [comment]
+ me

Im using multiple cron instances to schedule a crawler. but when a call callback i dont know what crawler i should to call. Is like:
```
function(name){
    cron.schedule('* * * * *', (name) => { callCrawler(name) }) 
}
```
Could be interesting use options field to implement a parameter input like.
options: {
    scheduler: true,
    params: "myCallbackParam"
}
```

thank you
