### ISSUE TITLE
install in docker container

### ISSUE THREAD

**Issue by denis-adobe** [node-cron/node-cron#187]
Hi
node-cron@^1.2.1 cant be installed via Dockerfile
but when i attach a console to that container and run npm install it compiles
below you can see my Dockerfile content
can someone reproduce the this?

**OS infos**
➜ uname -a
Linux denis-B450M-DS3H 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Docker version**
➜ docker -v
Docker version 19.03.1, build 74b1e89
**Project Structure**
➜ tree wpbackend/node/ -L 1
wpbackend/node/
├── basicauth.js
├── config
├── css.sh
├── gruntfile.js
├── index.js
├── js
├── node_modules
├── package.json
├── package-lock.json
├── public
├── templates
├── uploads
├── uploads_system
└── views

8 directories, 6 files

**Dockerfile**
```
FROM node:8
WORKDIR /node
COPY ./node/ .
RUN npm install -g nodemon
RUN npm install
RUN npm install --save node-cron@^1.2.1
CMD ["nodemon", "--inspect=0.0.0.0:9229","index.js"]
```

**I recieve following Error Message:**

➜ docker logs -f 4e3699cdf80de5f36d3eb5fb0cda1bb0ccf5ad8e4f9ff3b30b4fdeebc31a7eb7
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect=0.0.0.0:9229 index.js`
Debugger listening on ws://0.0.0.0:9229/96910724-7762-4f15-8282-7398eb004100
For help see https://nodejs.org/en/docs/inspector
config.js -> loading localhost config
module.js:550
    throw err;
    ^

Error: Cannot find module 'node-cron'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node/index.js:130:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[nodemon] app crashed - waiting for file changes before starting...

**After rerun npm install in the Container the node-cron package is installed and the Container runs without an Error**

root@4e3699cdf80d:/node# npm install

> node-expat@2.3.17 install /node/node_modules/node-expat
> node-gyp rebuild

make: Entering directory '/node/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
../deps/libexpat/lib/xmlparse.c: In function 'gather_time_entropy':
../deps/libexpat/lib/xmlparse.c:780:7: warning: variable 'gettimeofday_res' set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  COPY Release/node_expat.node
make: Leaving directory '/node/node_modules/node-expat/build'

> ursa@0.9.4 install /node/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/node/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
  COPY Release/ursaNative.node
make: Leaving directory '/node/node_modules/ursa/build'

> bcrypt@3.0.3 install /node/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[bcrypt] Success: "/node/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> sleep@3.0.1 install /node/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/node/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make: Leaving directory '/node/node_modules/sleep/build'
added 986 packages from 696 contributors and audited 2710 packages in 23.789s
found 154 vulnerabilities (40 low, 35 moderate, 79 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@4e3699cdf80d:/node# 

I am thankful for every helpful advice.

**Comment by denis-adobe** [comment]
ok this isnt an issue of node-cron i just saw that the docker container actually doesnt create the node_modules folder
