### ISSUE TITLE
Unintentional catch?

### ISSUE THREAD

**Issue by swapsCAPS** [node-cron/node-cron#223]
I would like to let my program crash when a promise throws an error.
It seems like promises are being caught by node-cron.
```javascript
const cron = require('node-cron')

process.once('unhandledRejection', (reason) => {
  console.log('unhandledRejection', reason)
  throw reason
})

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms))

const willThrow = async () => {
  await sleep(50)
  throw new Error('Ouch!')
}

cron.schedule('*/1 * * * * *', () => willThrow())

const fail = async () => {
  await sleep(2000)
  throw new Error('FAIL!')
}

fail()
```

output
```
▶ node node-cron-throw.js
Error: Ouch!
    at willThrow (/scripts/node-cron-throw.js:12:9)
Error: Ouch!
    at willThrow (/scripts/node-cron-throw.js:12:9)
unhandledRejection Error: FAIL!
    at fail (/scripts/node-cron-throw.js:19:9)
/scripts/node-cron-throw.js:5
  throw reason
  ^

Error: FAIL!
    at fail (/scripts/node-cron-throw.js:19:9)

```

**Comment by ShivKumarSaini** [comment]
Yes, I am facing the same issue. 
I want my program to recognise the Rejection of Promise running in a cron-job, but that rejection is caught by 'catch' handler of 'this.update' method written inside 'task.js' file. Is there any configuration option to bypass this to original caller method which is awaiting for settling of promise OR if this is an issue then let us know if the fix has been implemented ?

Please repsond! @node-cron

**Comment by ShivKumarSaini** [comment]
I have looked into it a bit deep, This is actually a wrong behaviour of node-cron's task API.
In case if developer's promise came out successful and resolve is called, then resolve works as expected. But in case if developer's promise comes out as error and rejection is called, then node-cron takes this reject call as if node-cron's task module has generated a fault.

**Comment by Wyctus** [comment]
What is the state of this issue now?

**Comment by swapsCAPS** [comment]
FWIW switched to `cron`

**Comment by Wyctus** [comment]
> FWIW switched to [cron](https://www.npmjs.com/package/cron)

Me too!
