### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SurgicalCrow** [node-cron/node-cron#266]
```0|m        | TypeError: Cannot read property 'replace' of undefined
0|m        |     at convertMonthName (/root/mustafa/node_modules/node-cron/src/convert-expression/month-names-conversion.js:10:31)
0|m        |     at interprete (/root/mustafa/node_modules/node-cron/src/convert-expression/month-names-conversion.js:16:23)
0|m        |     at interprete (/root/mustafa/node_modules/node-cron/src/convert-expression/index.js:54:22)
0|m        |     at validate (/root/mustafa/node_modules/node-cron/src/pattern-validation.js:76:29)
0|m        |     at new Task (/root/mustafa/node_modules/node-cron/src/task.js:40:3)
0|m        |     at Object.createTask [as schedule] (/root/mustafa/node_modules/node-cron/src/node-cron.js:43:16)
0|m        |     at XiaoClient.<anonymous> (/root/mustafa/index.js:574:8)
0|m        |     at Object.onceWrapper (events.js:420:28)
0|m        |     at XiaoClient.emit (events.js:326:22)
0|m        |     at WebSocketManager.triggerClientReady (/root/mustafa/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
0|m        |     at WebSocketManager.checkShardsReady (/root/mustafa/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
0|m        |     at WebSocketShard.<anonymous> (/root/mustafa/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
0|m        |     at WebSocketShard.emit (events.js:314:20)
0|m        |     at WebSocketShard.checkReady (/root/mustafa/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
0|m        |     at WebSocketShard.onPacket (/root/mustafa/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
0|m        |     at WebSocketShard.onMessage (/root/mustafa/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)```

**Comment by merencia** [comment]
Hi @SurgicalCrow , can you share the cron expression that you are using?
