### ISSUE TITLE
Can't find module scheduler

### ISSUE THREAD

**Issue by taco-engineer** [node-cron/node-cron#268]
My app worked until the update to 3.0.0 last week. When I push my code to Heroku, I get the following error: 

2021-03-15T14:32:41.187359+00:00 heroku[web.1]: Starting process with command `npm start`
2021-03-15T14:32:45.396693+00:00 app[web.1]:
2021-03-15T14:32:45.396707+00:00 app[web.1]: > service@1.0.0 start /app
2021-03-15T14:32:45.396707+00:00 app[web.1]: > node index.js
2021-03-15T14:32:45.396708+00:00 app[web.1]:
2021-03-15T14:32:45.969702+00:00 app[web.1]: internal/modules/cjs/loader.js:883
2021-03-15T14:32:45.969795+00:00 app[web.1]: throw err;
2021-03-15T14:32:45.969795+00:00 app[web.1]: ^
2021-03-15T14:32:45.969796+00:00 app[web.1]:
2021-03-15T14:32:45.969797+00:00 app[web.1]: Error: Cannot find module './scheduler'
2021-03-15T14:32:45.969797+00:00 app[web.1]: Require stack:
2021-03-15T14:32:45.969798+00:00 app[web.1]: - /app/node_modules/node-cron/src/scheduled-task.js
2021-03-15T14:32:45.969798+00:00 app[web.1]: - /app/node_modules/node-cron/src/node-cron.js
2021-03-15T14:32:45.969798+00:00 app[web.1]: - /app/index.js
2021-03-15T14:32:45.969799+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2021-03-15T14:32:45.969800+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2021-03-15T14:32:45.969800+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:952:19)
2021-03-15T14:32:45.969800+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:88:18)
2021-03-15T14:32:45.969802+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/node-cron/src/scheduled-task.js:5:19)
2021-03-15T14:32:45.969802+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-03-15T14:32:45.969803+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-03-15T14:32:45.969803+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
2021-03-15T14:32:45.969803+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-03-15T14:32:45.969804+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:952:19) {
2021-03-15T14:32:45.969805+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-03-15T14:32:45.969805+00:00 app[web.1]: requireStack: [
2021-03-15T14:32:45.969806+00:00 app[web.1]: '/app/node_modules/node-cron/src/scheduled-task.js',
2021-03-15T14:32:45.969806+00:00 app[web.1]: '/app/node_modules/node-cron/src/node-cron.js',
2021-03-15T14:32:45.969807+00:00 app[web.1]: '/app/index.js'
2021-03-15T14:32:45.969807+00:00 app[web.1]: ]
2021-03-15T14:32:45.969807+00:00 app[web.1]: }
2021-03-15T14:32:46.013024+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-15T14:32:46.013605+00:00 app[web.1]: npm ERR! errno 1
2021-03-15T14:32:46.026977+00:00 app[web.1]: npm ERR! service@1.0.0 start: `node index.js`
2021-03-15T14:32:46.027202+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-15T14:32:46.027458+00:00 app[web.1]: npm ERR!
2021-03-15T14:32:46.027685+00:00 app[web.1]: npm ERR! Failed at the service@1.0.0 start script.
2021-03-15T14:32:46.027892+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-15T14:32:46.041392+00:00 app[web.1]:
2021-03-15T14:32:46.042508+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-15T14:32:46.042700+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-15T14_32_46_028Z-debug.log
2021-03-15T14:32:46.121363+00:00 heroku[web.1]: Process exited with status 1
2021-03-15T14:32:46.190019+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by merencia** [comment]
Hi @taco-engineer 
I've made a test here and I can't reproduce that.

I've created a new project, installed `node-cron@3.0.0` and created a scheduled task and is working just fine.

Your project brakes only at Heroku?

**Comment by taco-engineer** [comment]
My project worked fine. Then the day of the new version, when I pushed new
code, not related to this library, the build failed. I did an update
***@***.*** and that pulled version 3.0.0. After that is when I
started getting the error. I haven't found any way to fix it through
updating or deleting packages. When I comment out the node-chron code it
runs fine.

**Comment by cloudyeng** [comment]
I had the same problem then I installed 'uuid' package ( 'npm i uuid'  ) and it worked.

**Comment by cloudyeng** [comment]
I had the same problem. I installed uuid package and it worked.
_>npm i uuid_
